version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    env_file: ./backend/.env
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=todo_pass
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - mysqldb_data:/var/lib/mysql
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306

  webapi:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    image: webapi
    env_file: ./backend/.env
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: nest_todo_api
    depends_on: 
      - mysqldb
    volumes: 
      - ./backend:/app
      - /app/node_modules
      - /app/node_modules/bcrypt/

  webapp:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: webapp
    ports:
      - 3001:3000
    container_name: react_todo_webapp
    depends_on:
      - webapi
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysqldb_data:
  nest_todo_api_data:
  react_todo_webapp_data: